app:
  log_level: info

kafka:
  brokers: localhost:9092
  security_protocol: plaintext
  ssl:
    ca_location: /app/cert/kafka_ca.pem
    certificate_location: /app/cert/app_cert.pem
    key_location: /app/cert/app_key.pem
    key_password:
  consumer_group: adt-to-fhir
  input_topic: adt-hl7
  output_topic: adt-fhir
  offset_reset: earliest

fhir:
  meta_source: "#orbis_adt"
  facility_id: "12345678"
  person:
    profile: https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/Patient|2026.0.0
    system: https://fhir.diz.uni-marburg.de/sid/patient-id
    other_insurance_system: https://fhir.diz.uni-marburg.de/sid/patient-other-insurance-id
  fall:
    profile: https://www.medizininformatik-initiative.de/fhir/core/modul-fall/StructureDefinition/KontaktGesundheitseinrichtung|2026.0.0
    system: https://fhir.diz.uni-marburg.de/sid/encounter-id
    institut_kennzeichen_system: http://fhir.de/sid/arge-ik/iknr
    einrichtungskontakt:
      system: https://fhir.diz.uni-marburg.de/sid/encounter-admit-id
    abteilungskontakt:
      system: https://fhir.diz.uni-marburg.de/sid/encounter-department-id
    versorgungsstellenkontakt:
      system: https://fhir.diz.uni-marburg.de/sid/encounter-caresite-id
  location:
    system_ward: https://fhir.diz.uni-marburg.de/sid/location-caresite-id
    system_room: https://fhir.diz.uni-marburg.de/sid/location-room-id
    system_bed: https://fhir.diz.uni-marburg.de/sid/location-bed-id
  condition:
    system: https://fhir.diz.uni-marburg.de/sid/condition-id
  observation:
    system: https://fhir.diz.uni-marburg.de/sid/observation-id
    profile_head_circumference: https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-kopfumfang|2026.0.1
    profile_weight: https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergewicht|2026.0.1
    profile_vital_status: https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/Vitalstatus|2026.0.0
    profile_height: https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/mii-pr-icu-muv-koerpergroesse|2026.0.0
