[package]
name = "processor-hl7v2"
version = "0.1.0"
edition = "2024"

[dependencies]
rdkafka = { version = "0.38", features = ["ssl", "cmake-build"] }
tokio = { version = "1.50", features = ["full"] }
log = "0.4"
env_logger = "0.11"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
futures = "0.3"
config = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
fhir-model = { version = "0.12", default-features = false, features = ["builders", "r4b"] }
hl7-parser = "0.3"
anyhow = "1.0"
thiserror = "2.0"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10"
regex = "1.12"
tokio-util = "0.7"
validator = { version = "0.21", features = ["derive"] }
opentelemetry = "0.32"
opentelemetry_sdk = "0.32"
opentelemetry-otlp = { version = "0.32", features = ["grpc-tonic"] }
itertools = "0.15"
uuid = { version = "1", features = ["v5"] }
fhir-core = { path = "../fhir-core" }
adt-config = { path = "../adt-config" }
derive_builder = "0.20"

[dev-dependencies]
rstest = "0.26"
mock-collector = "0.2"
reqwest = { version = "0.13", features = ["json"] }
adt-config = { path = "../adt-config", features = ["test-utils"] }